### ISSUE TITLE
jmpctl binary releases

### ISSUE THREAD

**Issue by mangelajo** [jumpstarter-dev/jumpstarter-controller#29]

**Comment by mangelajo** [comment]
Do you know if there is a way to get:
https://github.com/jumpstarter-dev/jumpstarter-controller/releases/tag/0.0.3

under the jmpctl name instead of jumpstarter-controller-xxxx.tar.gz ?

Also the action works for tags/releases but not for latest/main: we should disable trigger on push/merge to main

**Comment by NickCao** [comment]
Addressed in https://github.com/jumpstarter-dev/jumpstarter-controller/pull/34
