### ISSUE TITLE
Suppress "object has been modified" err in log

### ISSUE THREAD

**Issue by NickCao** [jumpstarter-dev/jumpstarter-controller#54]

**Comment by mangelajo** [comment]
I'd say:

1) Prevent when possible (patch vs update, or only patch/update only when it's absolutely necessary to avoid the gen field bump)
2) When the failure to update happens in controlled way
a) make sure that controller will retry
b) reduce the level and verbosity of the result ERROR->INFO and provide enough detail to trace possible issues
c) However, we should still be cautious of ERRORS in unexpected situations; we may still want to log those as errors.
