### ISSUE TITLE
Multi-arch images

### ISSUE THREAD

**Issue by mangelajo** [jumpstarter-dev/jumpstarter-controller#62]
https://docs.docker.com/build/ci/github-actions/multi-platform/

arm/v7 (best effort) + arm64 + amd64

**Comment by NickCao** [comment]
Python side: https://github.com/jumpstarter-dev/jumpstarter/pull/156

**Comment by NickCao** [comment]
Controller side: https://github.com/jumpstarter-dev/jumpstarter-controller/pull/64
